---
# https://devops.profitbricks.com/tutorials/install-and-configure-apache-kafka-on-ubuntu-1604-1/

#- name: update and upgrade repositories cache
#  apt:
#    update_cache: yes
#    upgrade: full

- include: java.yml
- include: kafka.yml
- include: vagrant.yml
