---
#######################################
# Example for use when
# skip echo, because kind == "Project"
- name: Echo
  command: echo "Echo - Kind {{ create_project_foo.result.kind }}"
  when:
      - create_project_foo.result.kind != "Project"
  register: echo
- debug: 
    msg: "{{ echo.stdout }}"
  when: echo.stdout is defined