---

- name: "Hello Ansible"
  command: echo "Hello Ansible"
  register: result

- debug: 
    msg:
      - "Echo-Result: {{ result.stdout }}"
      - "In Shell: '{{ lookup('env', 'SHELL') }}"
      - "I'm on Host: {{ ansible_host }} (through var: {{ var_host }})"
 